
package com.pvg.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PvgWebService", targetNamespace = "http://webservice.pvg.com/", wsdlLocation = "http://user-pc:8282/PvgWebService/PvgWebService?wsdl")
public class PvgWebService_Service
    extends Service
{

    private final static URL PVGWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException PVGWEBSERVICE_EXCEPTION;
    private final static QName PVGWEBSERVICE_QNAME = new QName("http://webservice.pvg.com/", "PvgWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://user-pc:8282/PvgWebService/PvgWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PVGWEBSERVICE_WSDL_LOCATION = url;
        PVGWEBSERVICE_EXCEPTION = e;
    }

    public PvgWebService_Service() {
        super(__getWsdlLocation(), PVGWEBSERVICE_QNAME);
    }

    public PvgWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PVGWEBSERVICE_QNAME, features);
    }

    public PvgWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, PVGWEBSERVICE_QNAME);
    }

    public PvgWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PVGWEBSERVICE_QNAME, features);
    }

    public PvgWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PvgWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PvgWebService
     */
    @WebEndpoint(name = "PvgWebServicePort")
    public PvgWebService getPvgWebServicePort() {
        return super.getPort(new QName("http://webservice.pvg.com/", "PvgWebServicePort"), PvgWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PvgWebService
     */
    @WebEndpoint(name = "PvgWebServicePort")
    public PvgWebService getPvgWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.pvg.com/", "PvgWebServicePort"), PvgWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PVGWEBSERVICE_EXCEPTION!= null) {
            throw PVGWEBSERVICE_EXCEPTION;
        }
        return PVGWEBSERVICE_WSDL_LOCATION;
    }

}
